config/routes.rb
Rails.application.routes.draw do
  resources :cat_rental_requests, only: [:index, :show, :new, :create]

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = ["red", "orange", "yellow", "green", "blue", "purple", "black", "white", "calico"]

  validates :name, :color, :sex, presence: true
  validates :color, inclusion: { in: COLORS, message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex"}

  has_many :cat_rental_requests, dependent: :destroy,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id

  def age
    now = Date.today
    difference_in_days = (now-birth_date).to_i
    (difference_in_days/365.25).to_i
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validate :overlapping_approved_requests

  belongs_to :cat,
    class_name: "Cat",
    foreign_key: :cat_id,
    primary_key: :id

  def overlapping_requests
    overlapping_requests = []
    all_requests = CatRentalRequest.all
    all_requests.each do |request|
      if (request.start_date..request.end_date).cover?(start_date)
        overlapping_requests << request unless request == self
      elsif (request.start_date..request.end_date).cover?(end_date)
        overlapping_requests << request unless request == self
      end
    end
    overlapping_requests
  end

  def overlapping_approved_requests
    overlapping_requests.each do |request|
      return false if (request.status == "APPROVED" && status == "APPROVED")
    end
    true
  end

  def approve!
    self.transaction do
      self.status = "APPROVED"
      self.save!
    end
    # if @cat_rental_request.save
    #   redirect_to cat_rental_requests_url
    # else
    #   @cat_rental_requests.destroy!
    #   render json: @cat_rental_request.errors.full_messages
    # end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
  end

  def show
  end

  def create
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)

    if @cat_rental_request.save
      redirect_to new_cat_rental_request_url
    else
      render :new
      p @cat_rental_request.errors.full_messages
    end
  end

  def new
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new
  end

  def approve!
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.transaction do
      status = "APPROVED"
      save
    end
    # if @cat_rental_request.save
    #   redirect_to cat_rental_requests_url
    # else
    #   @cat_rental_requests.destroy!
    #   render json: @cat_rental_request.errors.full_messages
    # end

  end

  private
  def cat_rental_request_params
    params
      .require(:cat_rental_request)
      .permit(:cat_id, :start_date, :end_date, :status)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])

  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cats_url
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :color, :sex, :birth_date, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/create.html.erb
<h1>CatRentalRequests#create</h1>
<p>Find me in app/views/cat_rental_requests/create.html.erb</p>

app/views/cat_rental_requests/index.html.erb
<h1>CatRentalRequests#index</h1>
<% CatRentalRequest.all.each do |request| %>
  <%= request %>
<% end %>

app/views/cat_rental_requests/new.html.erb
<h1>CatRentalRequests#new</h1>

<form action= "<%=cat_rental_requests_url%>" method = "POST">
  Name
    <select name='cat_rental_request[cat_id]'>
     <option value='<%=@cat_rental_request.cat_id%>'>
       <%= @cat_rental_request.cat ? @cat_rental_request.cat.name : ""%>
     </option>
       <%@cats.each do |cat| %>
         <option value='<%=cat.id%>'> <%= cat.name %> </option>
       <% end %>
    </select> <br>

Start Date
    <input type='date'
        name='cat_rental_request[start_date]'
        value= '<%= @cat_rental_request.start_date %>'> <br>

End Date
    <input type='date'
        name='cat_rental_request[end_date]'
        value= '<%= @cat_rental_request.end_date %>'> <br>



  <input type='submit'>

</form>

app/views/cat_rental_requests/show.html.erb
<h1>CatRentalRequests#show</h1>
<p>Find me in app/views/cat_rental_requests/show.html.erb</p>

app/views/cats/_form.html.erb
<% if @cat.persisted? %>
  <form action= "<%=cat_url(@cat)%>" method = "POST">
    <input type='hidden' value='PATCH' name='_method'/>
<% else %>
  <form action= "<%=cats_url%>" method = "POST">
<% end %>

  Name <input type='text'
            name='cat[name]'
            placeholder="gizmo..."
            value="<%= @cat.name%>"/> <br>

Sex <input type='radio'
           name='cat[sex]'
           value='M'/> Male
    <input type='radio'
           name='cat[sex]'
           value='F'/> Female <br>

Color <select name='cat[color]' >
        <option> <%=@cat.color%> </option>
          <% Cat::COLORS.each do |color| %>
            <option> <%= color %> </option>
          <% end %>
      </select> <br>

Birthday
  <input type='date'
         name='cat[birth_date]'
         value="<%=@cat.birth_date%>"> <br>

Description
  <textarea rows='5'
            cols='20'
            name='cat[description]'>
    <%=@cat.description%>
  </textarea> <br>


<input type="submit">

</form>

app/views/cats/edit.html.erb
  <%=render "form.html.erb"%>

app/views/cats/index.html.erb
<% @cats.each do |cat| %>
    <%=link_to cat.name, cat_url(cat)%> <br>
<% end %>

app/views/cats/new.html.erb
  <%=render "form.html.erb"%>

app/views/cats/show.html.erb
<head> <title> <% @cat.name %> </title> </head>

<body>
  <table>
    <% @cat.attributes.each do |attribute, value| %>
      <tr>
        <td> <%= attribute %> </td>
        <td> <%= value %> </td>
      </tr>
    <% end %>
  </table>

  <h3>Rental Requests</h3>
  <table>
    <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
      <%= request.start_date %> <br>
      <%= request.end_date %> <br>
      <%= request.status %> <br><br>
    <% end %>
  </table>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>